// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { envVars } from './src/app/config/env';
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envVars.DATABASE_URL,
  },
});